### ISSUE TITLE
Clicking PlayPauseView multiple times and toggling state makes the PlayPauseView forget its current status

### ISSUE THREAD

**Issue by bhavikmehta5491** [OHoussein/android-material-play-pause-view#3]
When the view is clicked multiple times, the boolean inside your class forgets its status and goes crazy.
It forgets its status and not changing to desired state when playPauseViewchange.change(true/false); is fired. please help

**Comment by alexeyvasilyev** [comment]
I have exactly the same issue while toggle animation is not finished.

**Comment by bhavikmehta5491** [comment]
@OHoussein : Thanks
